### ISSUE TITLE
Tooltip on navigation buttons

### ISSUE THREAD

**Issue by abhisheksimion** [almende/vis#1079]
Need to have tooltip on navigation buttons. http://plnkr.co/edit/oBjYUURG39swCVLMV4mI?p=preview

**Comment by felixhayashi** [comment]
Hi @abhisheksimion 

You can do this with css using the "before" selector.

```css
.vis-navigation .vis-button:hover:before {
          background: beige;
          display: block;
          color: black;
          padding: 3px;
          position: relative;
          border: 1px solid lightgray;
          width: 80px;
          left: -70px;
          top: -30px;
          z-index: 1000;
          text-align: center; }
        .vis-navigation .vis-button:hover.vis-up:before {
          left: 30px;
          content: "Scroll up"; }
        .vis-navigation .vis-button:hover.vis-down:before {
          left: 30px;
          content: "Scroll down"; }
        .vis-navigation .vis-button:hover.vis-right:before {
          left: 30px;
          content: "Scroll right"; }
        .vis-navigation .vis-button:hover.vis-left:before {
          left: 30px;
          content: "Scroll left"; }
        .vis-navigation .vis-button:hover.vis-zoomOut:before {
          content: "Zoom out"; }
        .vis-navigation .vis-button:hover.vis-zoomIn:before {
          content: "Zoom in"; }
        .vis-navigation .vis-button:hover.vis-zoomExtends:before {
          content: "Reset focus"; }
```

You can see how it looks at http://tiddlymap.org.

-Felix
