### ISSUE TITLE
Dynamically node add (over addNodeMode function & directly add to dataset) issue

### ISSUE THREAD

**Issue by pablo-xor** [almende/vis#1305]
Hi,

I found small but very problematic bug during dynamically adding new nodes on specified position. In brief, my app consist of four div blocks:
```html
        <div id="content">
            <div id="tools"></div>
            <div id="status"></div>
            <div id="graph"></div>
        </div>
```
```css
#tools {
    width: 250px;
    background: #393939;
    float: left;
    position: absolute;
    z-index: 200;
    border-bottom-right-radius: 10px;
    top: 30px;
    opacity: 0.9;
}

#graph {
    width: 100%;
    z-index: 100;
    height: 100%;
    cursor: crosshair;
    position: absolute;
}

#status {
    position: absolute;
    z-index: 200;
    bottom: 10px;
    right: 10px;
    color: black;
    font-style: italic;
    text-shadow:
        -1px -1px 0 #FFF,
        1px -1px 0 #FFF,
        -1px 1px 0 #FFF,
        1px 1px 0 #FFF;  
}
```
On default viewport (canvas {x: 0.0, y: 0.0}) is OK, but when I drag viewport very much with scale >= 1.0 node will be added to dataset without refereshing canvas. I tried "redraw" method but did not work. On small scale value (0.1) is OK and when I call method "fit" after first animation frame node becomes visible.
