### ISSUE TITLE
Editable timeline with read-only range items - wrong cursor on edges

### ISSUE THREAD

**Issue by thorstenfleischmann** [almende/vis#1554]
In a editable timeline with read-only items (range), the cursor on the edges still looks like you can move the end/start of the item. Which is not true for read-only items :-) This is a little bit confusing for some people.

The following css code fixes the issue
```css
.vis-range.vis-item.vis-readonly .vis-drag-left, .vis-range.vis-item.vis-readonly .vis-drag-right {
    cursor: auto;
}
```
