### ISSUE TITLE
How do I set the max width for groups in Timeline?

### ISSUE THREAD

**Issue by BulaSpirit** [almende/vis#1569]
In Timeline.js there used to be a Configuration Option called: "groupsWidth" by which one could over-ride the default behaviour and set the max width for groups. 
I can't seem to find an equivalent in vis.js.  
Is there a way to do it? 

Thanks!

**Comment by josdejong** [comment]
You can do that with css:

```css
.vis-labelset .vis-label .vis-inner {
  max-width: 100px;
}
```
