### ISSUE TITLE
Disable items resize on timeline 

### ISSUE THREAD

**Issue by chiarishow** [almende/vis#1719]
Hi,

is there an option to disable resizing of items on timeline?

I can't find this option anywhere in the docs.

Thank you!
Nikola

**Comment by josdejong** [comment]
Check out the docs regarding the configuration option `editable`.

**Comment by chiarishow** [comment]
yes, I can set the option updateTime to false, but then I can't resize or move any items. 

I'm interested on moving but not resizing. 

I can use the method onMoving to allow moving and not resizing but it's not an "elegant" solution. 

Thank you for the response.

**Comment by josdejong** [comment]
You can use callbacks `onMove` and `onMoving` to restrict changes in start and end of the item. Using that callback you can enforce keeping the duration the same.

http://visjs.org/docs/timeline/#Editing_Items

**Comment by chiarishow** [comment]
Ok, it's what I try in my previous comment. 

Thanks. I will try find a solution to disable the "resize" pointer.

**Comment by josdejong** [comment]
> I will try find a solution to disable the "resize" mouse pointer.

ah, that's a smart idea, this should do the trick:

```css
.vis-drag-left,
.vis-drag-right {
  pointer-events: none;
}
```

**Comment by chiarishow** [comment]
Perfect,

Thank you!

**Comment by jonas-lauber** [comment]
In order to only disable resizing (but not moving), one can set _**editable**_ property accordingly and set the following css:
```css
.vis-drag-left,
.vis-drag-right {
      display: none;
}
```
And thus won't even have to write any logic in _**onMoving**_.

In my case I want to disable resizing by default and only activate it when a given key is pressed. What I did is adding the following css (scss):

```css
.vis-item {
    .vis-drag-left,
    .vis-drag-right {
      display: none;
    }

    &.drag-activated {
      .vis-drag-left,
      .vis-drag-right {
        display: block;
        width: 50%;
        max-width: 50%;
      }
    }
}
```
Then once the given key is pressed down I add the class drag-activated on the currently selected item and remove it once the key is released. It works like a charm ^^ 
Hope it helps someone.
