### ISSUE TITLE
how to disable blue box oncontext  event?

### ISSUE THREAD

**Issue by FrissAnalytics** [almende/vis#1743]
Hi,

I was wondering, how can I disable the blue box that is shown e.g. in chrome, on a right click i.e oncontext event? It's tricky to freeze the browser to see what css needs to be changed. Unfortunately I couldn't spot the correct css line in vis.css.

kind regards, Herman

**Comment by FrissAnalytics** [comment]
for those who want to know, you can add this to your css:

```css
/* make sure chrome doesn't draw a blue box around the network drawing canvas on right click */
.vis-network {
 outline: 0;
}

```
