### ISSUE TITLE
How to access the group element which shows the group name....

### ISSUE THREAD

**Issue by Kaliph** [almende/vis#1905]
![example2](https://cloud.githubusercontent.com/assets/19877914/15987322/b41d862a-3024-11e6-82e9-fc3fd8e8a967.png)
I would like to access the group element of the timeline. So I can display a picture in it which change if a new status arrives. Is something like this possible? 
Let´s say one of the items rises a special value in the group timeline... and the group element of this timeline which shows the Name of this groups turns the background color into red. Is something like this possible? If u can help me please post a code example. Br Kaliph

**Comment by brichbe** [comment]
Yes it's possible.  The `content` property of your group Items can be HTML.  In your example image your group content is "11", but try changing that to some HTML that includes an `img` tag for the picture you want to display.  Use the `style` property to change the background color.

**Comment by mojoaxel** [comment]
You can access and change the group-label like so:
```css
.vis-timeline > .vis-panel > .vis-content > .vis-labelset > .vis-label:nth-child(10) > .vis.inner:after {
  content: '';
  background-image: url("upToDate.gif");
}
```
