### ISSUE TITLE
Timeline + Groups - Two cases of severe rendering issues

### ISSUE THREAD

**Issue by Rikk** [almende/vis#2032]
Using Timeline with Groups and stack=true (default).

## 1)
This issue took me a long time to figure out the cause...

**Severe rendering issues happen when we define `white-space: normal` for the class `.vis-item-content` and no fixed-width is defined.**

Basically, vis.js fails to calculate positions properly.

I made a modified version of the Groups demo:
http://jsbin.com/remukoqede/edit?html,output

Tip: because the demo creates random elements, some times (page reloads) it will be more clearly visible than others.

## 2)
When trying to center group labels in their containers, my first approach was this:

```css
.vis-labelset > .vis-label {
	display: table;
}
.vis-labelset > .vis-label > .vis-inner {
	display: table-cell;
	vertical-align: middle;
	text-align: center;
}
```

But this also was causing positioning issues for vis.js.
The workaround I found is using flexbox, despite its compatibility:

```css
.vis-labelset > .vis-label {
	display: flex;
	justify-content: center;
	align-items: center;
}
```

## 1+2)
In the configuration I'm building for a project I was getting an infinite amount of `WARNING: infinite loop in redraw?` and vis.js basically couldn't resize each group. You can see that it resizes pixel by pixel when timeline is being dragged in any direction.

http://jsbin.com/payugiyeyo/edit?html,output

**Comment by mojoaxel** [comment]
@Rikk Thanks for reporting this! This looks like a bug. I'll hope somebody finds the time to look into it.

**Comment by mojoaxel** [comment]
## Issue 1:
this is a bug. If BoxItems get initially rendered of the screen and the content-width is dynamic (word-wrap, no fixed width) than the box width is determined falsely. I fixed this by rendering all boxes initially in the visible range so, the width can be determined correctly. See Pull-Request #2035

## Issue 2:
This is the easiest solution:
```css
vis-labelset .vis-label .vis-inner {
    width: 100%;
    text-align: center;
    box-sizing: border-box;
}
```

## infinite loop:
see #450
