### ISSUE TITLE
Possibility to use onClick to show more info

### ISSUE THREAD

**Issue by 4integration** [almende/vis#2144]
Hi,

Is it possible to use onClick/onHover and to show a popup with HTML formatted text on timeline? If so I cannot find the docs or solution; grateful for any help.

/ Joacim

**Comment by yotamberk** [comment]
Currently there is no such option. It's a good feature request!

The way I did it is by injecting a popup via the `template` option. This can work but it really depends what you are using:
- Using pure html/css, you can inject via the `template` a div with your popup (you can add one manually with your HTML and CSS) with `display: none` and have it change to `display:block' with the css pseudo `:hover` on your item. 
- Using angular, you can use $compile to compile a popup directive straight to the item.
- Using jQuery, you can locate the selected item (via selected class on click) and attach a popup.
- Using react,  it's a bit of a problem. If you need specifications for this, I can supply more on how to go ahead with it.

For any of these examples in more details, you are welcome to contact me.

**Comment by 4integration** [comment]
Ok, thanks for your input @yotamberk 

I would like to keep it as simple as possible (pure html/css but since jQuery is already used that is an option) and have the data stored as JSON.
Do you have any example code that does this?

**Comment by yotamberk** [comment]
Hey @4integration ,
simply add to your timeline options:
```javascript
template: function(item) {
      html = '<div class="wrapper">' + item.content + ' <div class="popover"> more info about:' + item.content + '</div></div>'
      return html;
    }
```

and add style like this:
```css
 .popover {
      display: none;
      position: absolute;
      top: -20px;
      left: 0px;
      background: yellow;
      z-index: 1;
    }

    .wrapper:hover .popover {
      display: block;
    }
```
Ofcourse you can change the html and css as you want.
Hope that helps! =)
