### ISSUE TITLE
Fixate Timeline

### ISSUE THREAD

**Issue by albertotimoteo** [almende/vis#2552]
How can I fixate my div timeline, so it'll be always on the bottom of the screen?

**Comment by yotamberk** [comment]
Add to your css (assuming the dive has a class of `timeline`)
 ``` css
.timeline {
 position: fixed;
 Bottom: 0;
}
```
