### ISSUE TITLE
Timeline vertical scroll can be placed at right?

### ISSUE THREAD

**Issue by qwe852147** [almende/vis#3066]
Timeline vertical scroll at left  will call nested group click event when click scroll arrow . 

There has an example [https://jsfiddle.net/pochin/kqaa5qxk/](https://jsfiddle.net/pochin/kqaa5qxk/)
When vertical scroll arrow and group which has nestedgroup at the same highet  ,Click scroll arrow will call scroll arrow and group arrow(nestedgroup open or closed) function

**Comment by yotamberk** [comment]
add this: 
``` css
.vis-left.vis-panel.vis-vertical-scroll {
    direction: ltr;
}
```
Does this do the job?
