### ISSUE TITLE
Feature : distinguishing CSS / DOM or JS between past and future.

### ISSUE THREAD

**Issue by tatsujb** [almende/vis#3897]
Ok there's a line representing today. but that just makes us want to use that for the user. and right now there's nothing we can do.

say I want to stylize all items that are in the past differently. 

there's no way to do that right now.

**Comment by katjasmin** [comment]
Of course there is a way for that. You simply create a different style class for past items in CSS and then assign it to the all the past items in a method. I did this in a java method because i create all the item data in a java class and not in Javascript, but it should be possible with JS as well.

**Comment by tatsujb** [comment]
I see no practical way of doing it. Please share with me what you know.

**Comment by katjasmin** [comment]
Here is a snippet how the CSS could look like. I recommend using SASS or LESS to generate CSS if you're having a lot of different item classes to avoid spelling mistakes.

For example I give my past items more transparency.. (other part of the code will be posted tomorrow)

```css
.brand, .vis-item.vis-background.brand {
  background-color: #5FDDF9
  border-color: #5FDDF9
}

.brandPast, .vis-item.vis-background.brandPast {
  background-color: #5FDDF9;
  border-color: #5FDDF9;
   opacity: 0.5; 
}
```
