### ISSUE TITLE
another CustomTime cursor

### ISSUE THREAD

**Issue by myrises** [almende/vis#498]
**dist/vis.css:**

``` css
.vis.timeline .customtime {
  background-color: #6E94FF;
  width: 2px;
  cursor: move;
  z-index: 1;
}
```

**cursor: col-resize** much better looks <-||->
:yum:
