### ISSUE TITLE
end time change instead of item move during dragging range items

### ISSUE THREAD

**Issue by iphar** [almende/vis#609]
There is a problem with dragging range items.

The cursor indicates wheter you move the whole item (cross cursor) or change start/ endtime (horizontal arrow cursor). Fine.

But if you want to move an item and start dragging relatively close to the end (mouse shows correctly the cross cursor) then the dragging does an endtime change instead of moving. You can see that during dragging right the cursor also changes from cross to arrow.

Can be easily reproduced in http://visjs.org/examples/timeline/02_interactive.html with item4.

For me its a big problem as I sometimes have small items and you never find a valid point to move, as it always does the end time change although it shows the cross.
I hope I've explained it understandable :)

Thanks

**Comment by josdejong** [comment]
So if I understand you correctly, I open http://visjs.org/examples/timeline/02_interactive.html and zoom out such that item4 has as width of say 20 or 30 pixels. Well, yes, then the width of the area where you can move the item is zero. What you will have to do right now is zoom in first and then move the item. Do you have any ideas for a solution for this?

If this happens a lot in your application, you could alter the css of the drag areas on the left and right end of the range item. Change the width (24px) or the amount of pixels that they stick outside of the item (4px).

```css
.vis.timeline .item.range .drag-left {
  position: absolute;
  width: 24px;
  height: 100%;
  top: 0;
  left: -4px;

  cursor: w-resize;
}

.vis.timeline .item.range .drag-right {
  position: absolute;
  width: 24px;
  height: 100%;
  top: 0;
  right: -4px;

  cursor: e-resize;
}
```
