### ISSUE TITLE
Control of Item Padding

### ISSUE THREAD

**Issue by bbseven** [almende/vis#621]
I notice that we have control over item padding with options.padding, which must match the CSS. Padding is important for text rendering, however for a timeline that has a continuous stream, the padding causes the width of smaller items to scale strangely when zooming. For example, here is a timeline that is zoomed out:
![image](https://cloud.githubusercontent.com/assets/5885418/6080402/e4a01e26-adde-11e4-8902-d7c0d29ceafd.png)

Here it is zoomed in:
![image](https://cloud.githubusercontent.com/assets/5885418/6080434/4a90a4a8-addf-11e4-8648-27e9d5b19062.png)

The width of the second to fourth red bars doesn't change much when zooming in, which changes the apparent scale and magnitude of the small red bars when zoomed out.

When I set the padding to 0, the range items are rendered at the proper width, but the text looks terrible:
![image](https://cloud.githubusercontent.com/assets/5885418/6080493/c45949de-addf-11e4-851d-5de552456cc5.png)

Is this something that could be corrected?

Thanks!

**Comment by josdejong** [comment]
Turns out that the range items where displayed with a minimum width of 10 pixels, twice the width of the padding. I've fixed this by setting the 5px padding on the contents rather than the outer box.

I've pushed a fix to the `v4` branch, as this will be a breaking change: [18_range_overflow.html](http://visjs.org/examples/timeline/18_range_overflow.html) breaks, you need different css for that.

Applying the following css should do the trick for now:

```css
    .vis.timeline .item.range {
      padding: 0;
      overflow: hidden;
    }

    .vis.timeline .item.range .content {
      padding: 5px;
      box-sizing: border-box;
      overflow: visible;
    }
```
