### ISSUE TITLE
Timeline last group line has incorrect height

### ISSUE THREAD

**Issue by Jc-L** [almende/vis#654]
In a timeline with a different `.vlabel` font/height, the last-child of the group list has an incorrect height :
![last-child](https://cloud.githubusercontent.com/assets/9871632/6319328/f61c0304-bab8-11e4-8e78-62f29103a40e.png)

Here used with the following css :
```css
    .vis.timeline .labelset .vlabel {
      font-size: 7.5pt;    
      font-weight: 900;
    }
```
and javascript : 
```javascript
    var items = new vis.DataSet([]);
    var groups = [
      { id: 1, content: 'Group 1' },
      { id: 2, content: 'Group 2' },
      { id: 3, content: 'Group 3' }
    ];
    var options = { start: '2014-01-01', end: '2019-01-01' };
```
