### ISSUE TITLE
Indistinguishable "Edit node" and "Edit edge" buttons in the edition menu.

### ISSUE THREAD

**Issue by gomezgoiri** [almende/vis#688]
Both the "Edit node" and "Edit edge" classes share the same "edit" class.

Therefore, one cannot selectively disable only one of these two options by simply editing the CSS:
``` css
span.network-manipulationUI.edit {
	display: none;
}
```

I would suggest to assign different class names (or additional ones) to these buttons to enable this "feature".
